package com.zperkowski.exsys
import java.util.Arrays

declare enum Constatnts
    q_hoay("How old are you?"),
    q_dyhutlomaav("Do you have unlimited time, lots of money and a van?"),
    q_dypwtbacp("Do your parents want you to be a child prodigy?"),
    q_dycythsma("Do you consider yourself to have some musical ability?"),
    q_ayptpialofpt("Are you prepared to put in a lot of practice time?"),
    q_dyhnaaulos("Do you have nerves and an upper lip of steel?"),
    q_dywtdyfm("Do you want to drive your family mad?"),
    q_fyaac("Fancy yourself as a composer?"),
    q_aymmomm("Are you more Mozart or more McCartney?"),
    q_dywtbcoa("Do you want to be center of attention?"),
    q_dyfabojots("Do you fancy a bit of jazz on the side?"),
    q_dyhabh("Do you have a big house?"),
    q_dyhyn("Do you hate your neighbours?"),
    q_dywtpiao("Do you want to play in a orchestra?"),
    q_dylfm("Do you like folk music?"),
    q_dyelhw("Do you enjoy lifting heavy weights?"),
    q_dyhagsorat("Do you have a good sense of rhythm and timing?"),
    q_dyhaatsoc("Do you have an aversion to spit or condensation?"),
    q_dymbtbopj("Do you mind being the butt of people's jokes?"),
    q_dywac("Do you want a challenge?"),
    q_dymfar("Do you mind fiddling about reeds?"),
    q_labosae("Loud and bold or soft and elegant?"),
    q_dywtsos("Do you wish to sit or stand?"),
    q_dywtmia8cb("Do you want to moonlight in an 8os cover band?"),
    a_05("0-5 years old"),
    a_612("6-12 years old"),
    a_13("13+ years old"),
    a_yihagac("Yes! I've also got a chauffeur"),
    a_nr("Not really"),
    a_yiaa("Yes, I'm amazing"),
    a_y("Yes!"),
    a_niahjtp("No, I'm happy just to play"),
    a_nat("Not an total (?)"),
    a_nijwtgpaqap("No, I just want to get playing as quickly as possible"),
    a_ihs("I have some"),
    a_nq("Not quite"),
    a_tsjlm("That sounds just like me"),
    a_wnij("Wouldn't I just"),
    a_ianab("I'm not a bart!"),
    a_np("Not particularly"),
    a_m("Motzart"),
    a_mc("McCartney"),
    a_yiagbas("Yes, I'm gonna be a star"),
    a_yrob("Yes! Roll over Bethoven"),
    a_jinmiin("Jazz isn't music it's noise"),
    a_stc("Sure thing, cat!"),
    a_nriaatp("Not really, I'm a team player"),
    a_iliac("I live in a church"),
    a_tipor("There's plenty of room"),
    a_iimcab("It's more compact and bijou"),
    a_tmptmn("To many people, too much noise"),
    a_wap("With a passion"),
    a_iawfimh("I always wear flower in my hair"),
    a_ntaqn("No, they're quite nice"),
    a_iaomos("I'm often mistaken for Superman"),
    a_mlislas("My life is like a symphony!"),
    a_ianah("I'm not a hippy"),
    a_ianawb("I'm not a wing(?), but..."),
    a_yipsd("Yuck, I prefer staying dry"),
    a_ofiib("Only if it's baroque"),
    a_iioig("It's ok I guess"),
    a_iaahm("I'm a human metronome"),
    a_mah("Music above hygiene"),
    a_lits("Life's too short"),
    a_biogmarc("Bring it on, give me a real challenge!"),
    a_ilac("I like a challenge"),
    a_niats("No, I'm terribly sensitive"),
    a_ilagl("I love a good laugh"),
    a_tslwtmh("That sounds like way too much hassle"),
    a_ilfmt("I love frustrating manual tasks"),
    a_l("Louder!"),
    a_ep("Elegant, please"),
    a_iigmos("If I get my own solo"),
    a_dn("Definitely not"),
    a_sit("Sitteth"),
    a_stand("Standeth");

    fullName : String;
end


rule "Init"
   when
     qa : QA(getQuestion() == "", getAnswerd() == "")
   then
    System.out.println("Rule\tInit\t\t\t" + qa.toString() + " " + qa.countObservers());
    qa.change(Constatnts.q_hoay.getFullName(), Arrays.asList(Constatnts.a_05.getFullName(),
                                                            Constatnts.a_612.getFullName(),
                                                            Constatnts.a_13.getFullName()));
    retract(qa)
end

rule "Q_hoay_answered_05"
    when
        qa : QA(getQuestion() == Constatnts.q_hoay.getFullName(), getAnswerd() == Constatnts.a_05.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dypwtbacp.getFullName(),
            Arrays.asList(
                    Constatnts.a_y.getFullName(),
                    Constatnts.a_niahjtp.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "Q_hoay_answered_612"
    when
        qa : QA(getQuestion() == Constatnts.q_hoay.getFullName(), getAnswerd() == Constatnts.a_612.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_ayptpialofpt.getFullName(),
            Arrays.asList(
                    Constatnts.a_y.getFullName(),
                    Constatnts.a_nijwtgpaqap.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "Q_hoay_answered_13"
    when
        qa : QA(getQuestion() == Constatnts.q_hoay.getFullName(), getAnswerd() == Constatnts.a_13.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dyhutlomaav.getFullName(),
            Arrays.asList(
                    Constatnts.a_yihagac.getFullName(),
                    Constatnts.a_nr.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dypwtbacp_answered_y"
    when
        qa : QA(getQuestion() == Constatnts.q_dypwtbacp.getFullName(), getAnswerd() == Constatnts.a_y.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Violin");
        qa.deleteObservers();
    end

rule "q_dypwtbacp_answered_niahjtp"
    when
        qa : QA(getQuestion() == Constatnts.q_dypwtbacp.getFullName(), getAnswerd() == Constatnts.a_niahjtp.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_ayptpialofpt.getFullName(),
            Arrays.asList(
                    Constatnts.a_y.getFullName(),
                    Constatnts.a_nijwtgpaqap.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end


rule "Q_ayptpialofpt_answered_y"
    when
        qa : QA(getQuestion() == Constatnts.q_ayptpialofpt.getFullName(), getAnswerd() == Constatnts.a_y.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Piano");
        qa.deleteObservers();
    end

rule "Q_ayptpialofpt_answered_nijwtgpaqap"
    when
        qa : QA(getQuestion() == Constatnts.q_ayptpialofpt.getFullName(), getAnswerd() == Constatnts.a_nijwtgpaqap.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dywtdyfm.getFullName(),
            Arrays.asList(
                    Constatnts.a_wnij.getFullName(),
                    Constatnts.a_ianab.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dywtdyfm_answered_wnij"
    when
        qa : QA(getQuestion() == Constatnts.q_dywtdyfm.getFullName(), getAnswerd() == Constatnts.a_wnij.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Rossenbar (?)");
        qa.deleteObservers();
    end

rule "q_dywtdyfm_answered_ianab"
    when
        qa : QA(getQuestion() == Constatnts.q_dywtdyfm.getFullName(), getAnswerd() == Constatnts.a_ianab.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dyhabh.getFullName(),
            Arrays.asList(
                    Constatnts.a_iliac.getFullName(),
                    Constatnts.a_tipor.getFullName(),
                    Constatnts.a_iimcab.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dyhabh_answered_iliac"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhabh.getFullName(), getAnswerd() == Constatnts.a_iliac.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Organs");
        qa.deleteObservers();
    end

rule "q_dyhabh_answered_tipor"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhabh.getFullName(), getAnswerd() == Constatnts.a_tipor.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dywtpiao.getFullName(),
            Arrays.asList(
                    Constatnts.a_tmptmn.getFullName(),
                    Constatnts.a_mlislas.getFullName(),
                    Constatnts.a_ofiib.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dywtpiao_answered_tmptmn"
    when
        qa : QA(getQuestion() == Constatnts.q_dywtpiao.getFullName(), getAnswerd() == Constatnts.a_tmptmn.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Piano");
        qa.deleteObservers();
    end

rule "q_dywtpiao_answered_mlislas"
    when
        qa : QA(getQuestion() == Constatnts.q_dywtpiao.getFullName(), getAnswerd() == Constatnts.a_mlislas.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dyelhw.getFullName(),
            Arrays.asList(
                    Constatnts.a_iaomos.getFullName(),
                    Constatnts.a_ianawb.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dyhabh_answered_iimcab"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhabh.getFullName(), getAnswerd() == Constatnts.a_iimcab.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dyhyn.getFullName(),
            Arrays.asList(
                    Constatnts.a_wap.getFullName(),
                    Constatnts.a_ntaqn.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "Q_dyhutlomaav_answered_yihagac"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhutlomaav.getFullName(), getAnswerd() == Constatnts.a_yihagac.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Hurp");
        qa.deleteObservers();
    end

rule "Q_dyhutlomaav_answered_nr"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhutlomaav.getFullName(), getAnswerd() == Constatnts.a_nr.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dycythsma.getFullName(),
            Arrays.asList(
                    Constatnts.a_yiaa.getFullName(),
                    Constatnts.a_nat.getFullName(),
                    Constatnts.a_ihs.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dyhnaaulos_answered_nq"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhnaaulos.getFullName(), getAnswerd() == Constatnts.a_nq.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Piano");
        qa.deleteObservers();
    end

rule "q_dyhnaaulos_answered_tsjlm"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhnaaulos.getFullName(), getAnswerd() == Constatnts.a_tsjlm.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("French horn");
        qa.deleteObservers();
    end


rule "Q_dycythsma_answered_yiaa"
    when
        qa : QA(getQuestion() == Constatnts.q_dycythsma.getFullName(), getAnswerd() == Constatnts.a_yiaa.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dyhnaaulos.getFullName(),
            Arrays.asList(
                    Constatnts.a_tsjlm.getFullName(),
                    Constatnts.a_nq.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "Q_dycythsma_answered_ihs"
    when
        qa : QA(getQuestion() == Constatnts.q_dycythsma.getFullName(), getAnswerd() == Constatnts.a_ihs.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_fyaac.getFullName(),
            Arrays.asList(
                    Constatnts.a_yrob.getFullName(),
                    Constatnts.a_np.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "Q_dycythsma_answered_nat"
    when
        qa : QA(getQuestion() == Constatnts.q_dycythsma.getFullName(), getAnswerd() == Constatnts.a_nat.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Comb");
        qa.deleteObservers();
    end

rule "q_fyaac_answered_y"
    when
        qa : QA(getQuestion() == Constatnts.q_fyaac.getFullName(), getAnswerd() == Constatnts.a_y.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_aymmomm.getFullName(),
            Arrays.asList(
                    Constatnts.a_m.getFullName(),
                    Constatnts.a_mc.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_fyaac_answered_np"
    when
        qa : QA(getQuestion() == Constatnts.q_fyaac.getFullName(), getAnswerd() == Constatnts.a_np.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dywtbcoa.getFullName(),
            Arrays.asList(
                    Constatnts.a_yiagbas.getFullName(),
                    Constatnts.a_nriaatp.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dywtbcoa_answered_yiagbas"
    when
        qa : QA(getQuestion() == Constatnts.q_dywtbcoa.getFullName(), getAnswerd() == Constatnts.a_yiagbas.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Piano");
        qa.deleteObservers();
    end

rule "q_dywtbcoa_answered_nriaatp"
    when
        qa : QA(getQuestion() == Constatnts.q_dywtbcoa.getFullName(), getAnswerd() == Constatnts.a_nriaatp.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dyhabh.getFullName(),
            Arrays.asList(
                    Constatnts.a_iliac.getFullName(),
                    Constatnts.a_tipor.getFullName(),
                    Constatnts.a_iimcab.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_aymmomm_answered_m"
    when
        qa : QA(getQuestion() == Constatnts.q_aymmomm.getFullName(), getAnswerd() == Constatnts.a_m.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Piano");
        qa.deleteObservers();
    end

rule "q_aymmomm_answered_mc"
    when
        qa : QA(getQuestion() == Constatnts.q_aymmomm.getFullName(), getAnswerd() == Constatnts.a_mc.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Acoustic guitar");
        qa.deleteObservers();
    end

rule "q_dyfabojots_answered_jinmiin"
    when
        qa : QA(getQuestion() == Constatnts.q_dyfabojots.getFullName(), getAnswerd() == Constatnts.a_jinmiin.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Tube");
        qa.deleteObservers();
    end

rule "q_dyfabojots_answered_stc"
    when
        qa : QA(getQuestion() == Constatnts.q_dyfabojots.getFullName(), getAnswerd() == Constatnts.a_stc.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Double bass");
        qa.deleteObservers();
    end

rule "q_dyhyn_answered_wap"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhyn.getFullName(), getAnswerd() == Constatnts.a_wap.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dyhagsorat.getFullName(),
            Arrays.asList(
                    Constatnts.a_iaahm.getFullName(),
                    Constatnts.a_iioig.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dyhagsorat_answered_iaahm"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhagsorat.getFullName(), getAnswerd() == Constatnts.a_iaahm.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Percussion");
        qa.deleteObservers();
    end

rule "q_dyhagsorat_answered_iioig"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhagsorat.getFullName(), getAnswerd() == Constatnts.a_iioig.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Trumpet");
        qa.deleteObservers();
    end

rule "q_dyhyn_answered_ntaqn"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhyn.getFullName(), getAnswerd() == Constatnts.a_ntaqn.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dylfm.getFullName(),
            Arrays.asList(
                    Constatnts.a_ianah.getFullName(),
                    Constatnts.a_iawfimh.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dylfm_answered_ianah"
    when
        qa : QA(getQuestion() == Constatnts.q_dylfm.getFullName(), getAnswerd() == Constatnts.a_ianah.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Digital piano");
        qa.deleteObservers();
    end

rule "q_dylfm_answered_iawfimh"
    when
        qa : QA(getQuestion() == Constatnts.q_dylfm.getFullName(), getAnswerd() == Constatnts.a_iawfimh.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Acoustic guitar");
        qa.deleteObservers();
    end

rule "q_dyelhw_answered_ianawb"
    when
        qa : QA(getQuestion() == Constatnts.q_dyelhw.getFullName(), getAnswerd() == Constatnts.a_ianawb.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dyhaatsoc.getFullName(),
            Arrays.asList(
                    Constatnts.a_mah.getFullName(),
                    Constatnts.a_yipsd.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dyhaatsoc_answered_mah"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhaatsoc.getFullName(), getAnswerd() == Constatnts.a_mah.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dywac.getFullName(),
            Arrays.asList(
                    Constatnts.a_ilac.getFullName(),
                    Constatnts.a_biogmarc.getFullName(),
                    Constatnts.a_lits.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dyhaatsoc_answered_yipsd"
    when
        qa : QA(getQuestion() == Constatnts.q_dyhaatsoc.getFullName(), getAnswerd() == Constatnts.a_yipsd.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dymbtbopj.getFullName(),
            Arrays.asList(
                    Constatnts.a_ilagl.getFullName(),
                    Constatnts.a_niats.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dyelhw_answered_iaomos"
    when
        qa : QA(getQuestion() == Constatnts.q_dyelhw.getFullName(), getAnswerd() == Constatnts.a_iaomos.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dyfabojots.getFullName(),
            Arrays.asList(
                    Constatnts.a_jinmiin.getFullName(),
                    Constatnts.a_stc.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dymbtbopj_answered_ilagl"
    when
        qa : QA(getQuestion() == Constatnts.q_dymbtbopj.getFullName(), getAnswerd() == Constatnts.a_ilagl.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Viola");
        qa.deleteObservers();
    end


rule "q_dymbtbopj_answered_niats"
    when
        qa : QA(getQuestion() == Constatnts.q_dymbtbopj.getFullName(), getAnswerd() == Constatnts.a_niats.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Cello");
        qa.deleteObservers();
    end

rule "q_dywac_answered_biogmarc"
    when
        qa : QA(getQuestion() == Constatnts.q_dywac.getFullName(), getAnswerd() == Constatnts.a_biogmarc.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Oboe");
        qa.deleteObservers();
    end

rule "q_dywac_answered_ilac"
    when
        qa : QA(getQuestion() == Constatnts.q_dywac.getFullName(), getAnswerd() == Constatnts.a_ilac.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Bassoon");
        qa.deleteObservers();
    end

rule "q_dywac_answered_lits"
    when
        qa : QA(getQuestion() == Constatnts.q_dywac.getFullName(), getAnswerd() == Constatnts.a_lits.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dymfar.getFullName(),
            Arrays.asList(
                    Constatnts.a_tslwtmh.getFullName(),
                    Constatnts.a_ilfmt.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dymfar_answered_tslwtmh"
    when
        qa : QA(getQuestion() == Constatnts.q_dymfar.getFullName(), getAnswerd() == Constatnts.a_tslwtmh.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_labosae.getFullName(),
            Arrays.asList(
                    Constatnts.a_l.getFullName(),
                    Constatnts.a_ep.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_dymfar_answered_ilfmt"
    when
        qa : QA(getQuestion() == Constatnts.q_dymfar.getFullName(), getAnswerd() == Constatnts.a_ilfmt.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.deleteObservers();
        QA new_qa = new QA(Constatnts.q_dywtmia8cb.getFullName(),
            Arrays.asList(
                    Constatnts.a_iigmos.getFullName(),
                    Constatnts.a_dn.getFullName()
                    ),
                    qa.getObserver());
        insert(new_qa);
    end

rule "q_labosae_answered_l"
    when
        qa : QA(getQuestion() == Constatnts.q_labosae.getFullName(), getAnswerd() == Constatnts.a_l.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Trumpet");
        qa.deleteObservers();
    end

rule "q_labosae_answered_ep"
    when
        qa : QA(getQuestion() == Constatnts.q_labosae.getFullName(), getAnswerd() == Constatnts.a_ep.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Flute");
        qa.deleteObservers();
    end

rule "q_dywtsos_answered_sit"
    when
        qa : QA(getQuestion() == Constatnts.q_dywtsos.getFullName(), getAnswerd() == Constatnts.a_sit.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Lute");
        qa.deleteObservers();
    end

rule "q_dywtsos_answered_stand"
    when
        qa : QA(getQuestion() == Constatnts.q_dywtsos.getFullName(), getAnswerd() == Constatnts.a_stand.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Harpsichord");
        qa.deleteObservers();
    end

rule "q_dywtmia8cb_answered_iigmos"
    when
        qa : QA(getQuestion() == Constatnts.q_dywtmia8cb.getFullName(), getAnswerd() == Constatnts.a_iigmos.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Saxophone");
        qa.deleteObservers();
    end

rule "q_dywtmia8cb_answered_dn"
    when
        qa : QA(getQuestion() == Constatnts.q_dywtmia8cb.getFullName(), getAnswerd() == Constatnts.a_dn.getFullName())
    then
        System.out.println("Rule: " + qa.toString() + " " + qa.getQuestion() + " answer:\t" + qa.getAnswerd());
        qa.sendInfo("Clarinet");
        qa.deleteObservers();
    end
