package family
rule "Init"
	when
	then
		Person maria          = new Person("Maria");
		Person ewa            = new Person("Ewa");
		Person agata          = new Person("Agata");
		Person anna           = new Person("Anna");
		Person agnieszka      = new Person("Agnieszka");
		Person beata          = new Person("Beata");
		Person iwona          = new Person("Iwona");
		Person joanna         = new Person("Joanna");
		Person piotr          = new Person("Piotr");
		Person adam           = new Person("Adam");
		Person marek          = new Person("Marek");
		Person robert         = new Person("Robert");
		Person jan            = new Person("Jan");
		Person krzysztof      = new Person("Krzysztof");
		Person radek          = new Person("Radek");
		Person darek          = new Person("Darek");
		Person tomek          = new Person("Tomek");
		Person jacek          = new Person("Jacek");

		insert(new Relation(maria,marek,"parent"));
		insert(new Relation(maria,agata,"parent"));
		insert(new Relation(maria,jan,"parent"));
		insert(new Relation(piotr,marek,"parent"));
		insert(new Relation(piotr,agata,"parent"));
		insert(new Relation(piotr,jan,"parent"));
		insert(new Relation(ewa,anna,"parent"));
		insert(new Relation(ewa,joanna,"parent"));
		insert(new Relation(ewa,krzysztof,"parent"));
		insert(new Relation(adam,anna,"parent"));
		insert(new Relation(adam,joanna,"parent"));
		insert(new Relation(adam,krzysztof,"parent"));
		insert(new Relation(agata,radek,"parent"));
		insert(new Relation(agata,beata,"parent"));
		insert(new Relation(robert,radek,"parent"));
		insert(new Relation(robert,beata,"parent"));
		insert(new Relation(anna,darek,"parent"));
		insert(new Relation(anna,tomek,"parent"));
		insert(new Relation(jan,darek,"parent"));
		insert(new Relation(jan,tomek,"parent"));
		insert(new Relation(agnieszka,jacek,"parent"));
		insert(new Relation(agnieszka,iwona,"parent"));
		insert(new Relation(krzysztof,jacek,"parent"));
		insert(new Relation(krzysztof,iwona,"parent"));
        System.out.println("Family \t Rule Init fired");
end

rule "Woman"
    when
        r : Relation(people[0].toString() matches ".*a");
    then
        r.people[0].gender = Person.Gender.WOMEN;
        System.out.println("Family \t Rule Woman fired for " + r.people[0].toString() + " " + r.people[0].getGender());
    end

rule "Man"
    when
        r : Relation(people[0].toString() not matches ".*a");
    then
        r.people[0].gender = Person.Gender.MEN;
        System.out.println("Family \t Rule Man fired for " + r.people[0].toString() + " " + r.people[0].getGender());
    end

// TODO: Find why rules below doesn't fire

rule "Father"
    when
        r : Relation(relation.equals("parent"), people[0].getGender() == Person.Gender.MEN);
    then
        insert(new Relation(r.people[0], r.people[1], "father"));
        System.out.println("Family \t Rule Father fired for " + r.people[0].toString() + " and " + r.people[1].toString());
    end

rule "Mother"
    when
        r : Relation(relation.equals("parent"), people[0].getGender() == Person.Gender.WOMEN);
    then
        insert(new Relation(r.people[0], r.people[1], "mother"));
        System.out.println("Family \t Rule Mother fired for " + r.people[0].toString() + " and " + r.people[1].toString());
    end
