package fire
rule "Smoke"
   when
     Measurement(isSmoke(), getTemp() > 150)
   then
     System.out.print("There is smoke!\n");
     insert(new Fire());
end

rule "Fire"
   when
     Fire()
   then
     insert(new Phone(112));
     System.out.print("The fire is on!\n");
end

rule "Phone"
    when
        p : Phone();
    then
        System.out.print("Call " + p.getNumber() + "!\n");
    end

rule "Firefighter"
    when
        ff : Firefighter()
        f: Fire()
    then
        System.out.print("A firefighter " + ff.getName() + " arrived!\n");
        retract(f)
        System.out.printf("Fire extinguished\n");
    end

rule "FirefighterDone"
    when
        ff : Firefighter()
        not Fire()
    then
        System.out.printf("Firefighter is leaving\n");
    end
